'use client';

import { useState, useRef, useCallback, useEffect } from 'react';
import dynamic from 'next/dynamic';
import Webcam from 'react-webcam';
import NoiseGradientCanvas from '@/components/NoiseGradientCanvas';
import ControlPanel from '@/components/ControlPanel';
import AboutButton from '@/components/AboutButton';
import { DEFAULT_NOISE_PARAMS, NoiseParams } from '@/lib/types';
import { spacing, typography, colors, interaction } from '@/lib/designTokens';

// Dynamically import UniformRenderer with no SSR
const UniformRenderer = dynamic(() => import('@/components/UniformRenderer'), {
  ssr: false,
  loading: () => (
    <div className="w-full h-full flex items-center justify-center bg-gray-900">
      <p className="text-white">Loading 3D renderer...</p>
    </div>
  ),
});

export default function Home() {
  const [params, setParams] = useState<NoiseParams>(DEFAULT_NOISE_PARAMS);
  const [viewMode, setViewMode] = useState<'2d' | '3d'>('3d');
  const [showNameModal, setShowNameModal] = useState(false);
  const [uniformName, setUniformName] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const webcamRef = useRef<Webcam>(null);

  // Force re-render shader on initial load
  useEffect(() => {
    const timer = setTimeout(() => {
      // Trigger a params update by setting the same values
      setParams(prev => ({ ...prev }));
    }, 150); // Slight delay after component mount

    return () => clearTimeout(timer);
  }, []);

  const handleWebcamError = useCallback((error: string | DOMException) => {
    console.error('Webcam error:', error);
    alert('Unable to access webcam. Please check your camera permissions.');
  }, []);

  const handleWebcamLoad = useCallback(() => {
    console.log('Webcam loaded successfully');
    if (webcamRef.current?.video) {
      console.log('Webcam video element:', webcamRef.current.video);
      console.log('Video dimensions:', webcamRef.current.video.videoWidth, 'x', webcamRef.current.video.videoHeight);
    }
  }, []);

  const handleArchiveUniform = () => {
    setShowNameModal(true);
  };

  const handleSaveUniform = async () => {
    if (!uniformName.trim()) {
      alert('Please enter a name for the uniform');
      return;
    }

    setIsSaving(true);
    try {
      const { createClient } = await import('@supabase/supabase-js');
      const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
      );

      // Prepare data for insertion
      // Note: 'id' is auto-generated by Supabase, so we don't include it
      const playerData: Record<string, string | number | null> = {
        'Player Name': uniformName.trim(),
        'Position': 'Custom',
        'Description': `${uniformName.trim()}님이 직접 커스텀한 유니폼입니다`,
        'Saturation': params.saturation,
        'Amplitude': params.amplitude,
        'Lacunarity': params.lacunarity,
        'Grain': params.gain,
        'Warp Strength': params.warpStrength,
      };

      // Add color stops data
      params.colorStops.forEach((stop, index) => {
        if (index < 9) {
          const portions = [];
          for (let i = 0; i < params.colorStops.length; i++) {
            if (i === 0) {
              portions.push(params.colorStops[0].position * 100);
            } else {
              portions.push((params.colorStops[i].position - params.colorStops[i - 1].position) * 100);
            }
          }

          playerData[`Teams/${index}/Color`] = stop.color;
          playerData[`Teams/${index}/Percentage`] = portions[index].toFixed(0);
          playerData[`Teams/${index}/Team`] = `Color ${index + 1}`;
          playerData[`Teams/${index}/Years`] = null;
        }
      });

      const { error } = await supabase
        .from('Players')
        .insert([playerData])
        .select();

      if (error) {
        console.error('Error saving uniform:', error);
        console.error('Error details:', JSON.stringify(error, null, 2));
        console.error('Player data being inserted:', playerData);
        alert(`Failed to save uniform: ${error.message || JSON.stringify(error)}`);
      } else {
        alert('Uniform saved successfully!');
        setShowNameModal(false);
        setUniformName('');
      }
    } catch (error) {
      console.error('Error saving uniform:', error);
      alert('Failed to save uniform. Please try again.');
    } finally {
      setIsSaving(false);
    }
  };

  const handleDownload = () => {
    // Find the canvas element (works for both 2D and 3D)
    const canvas = document.querySelector('canvas');
    if (canvas) {
      try {
        // Convert canvas to PNG data URL
        const dataURL = canvas.toDataURL('image/png');

        // Create download link
        const link = document.createElement('a');
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        link.download = `a2f-${viewMode}-${timestamp}.png`;
        link.href = dataURL;

        // Trigger download
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      } catch (error) {
        console.error('Download failed:', error);
        alert('Download failed. Please try again.');
      }
    } else {
      alert('Canvas not found. Please wait for the render to complete.');
    }
  };

  return (
    <div className="relative w-screen h-screen overflow-hidden" style={{ backgroundColor: '#000000' }}>
      {/* Control Panel - Below Navigation */}
      <div
        className="absolute"
        style={{
          top: 'calc(25px + 40px + 15px)',
          left: spacing[25],
          display: 'flex',
          flexDirection: 'column',
          gap: '10px',
          zIndex: 100,
        }}
      >
        <ControlPanel
          params={params}
          onParamsChange={setParams}
          viewMode={viewMode}
          onViewModeChange={setViewMode}
        />

        {/* Archive Uniform Button */}
        <button
          onClick={handleArchiveUniform}
          style={{
            padding: '8px 12px',
            backgroundColor: '#000000',
            borderRadius: '6px',
            color: colors.dark.label.primary,
            fontSize: '14px',
            fontFamily: 'Helvetica, Arial, sans-serif',
            fontWeight: 400,
            border: 'none',
            transition: `all ${interaction.duration.normal} ${interaction.easing.standard}`,
            cursor: 'pointer',
            minHeight: '32px',
            minWidth: '284px',
          }}
        >
          Archive Uniform
        </button>

        {/* Export Uniform Button */}
        <button
          onClick={handleDownload}
          style={{
            padding: '8px 12px',
            backgroundColor: '#000000',
            borderRadius: '6px',
            color: colors.dark.label.primary,
            fontSize: '14px',
            fontFamily: 'Helvetica, Arial, sans-serif',
            fontWeight: 400,
            border: 'none',
            transition: `all ${interaction.duration.normal} ${interaction.easing.standard}`,
            cursor: 'pointer',
            minHeight: '32px',
            minWidth: '284px',
          }}
        >
          Export Uniform
        </button>
      </div>

      {/* About Button */}
      <AboutButton />

      {/* Info Box - Bottom Right */}
      <div
        className="absolute"
        style={{
          bottom: spacing[28],
          right: spacing[25],
          zIndex: 100,
          backgroundColor: 'rgba(255, 255, 255, 0.95)',
          backdropFilter: 'blur(20px)',
          borderRadius: '12px',
          padding: '12px',
          boxShadow: '0 8px 32px rgba(0, 0, 0, 0.15)',
          minWidth: '283px',
          minHeight: '83.87px',
        }}
      >
        <h2
          style={{
            fontSize: '14px',
            fontFamily: 'Helvetica, Arial, sans-serif',
            fontWeight: 400,
            color: 'rgba(0, 0, 0, 0.9)',
            marginBottom: spacing[8],
          }}
        >
          {viewMode === '2d' ? '2D Uniform Preview' : '3D Uniform Preview'}
        </h2>
        <div
          style={{
            width: '100%',
            height: '1px',
            backgroundColor: 'rgba(0, 0, 0, 0.1)',
            marginBottom: spacing[8],
          }}
        />
        <p
          style={{
            fontSize: '10px',
            fontFamily: 'Helvetica, Arial, sans-serif',
            fontWeight: 400,
            color: 'rgba(0, 0, 0, 0.7)',
            lineHeight: typography.lineHeight.relaxed,
          }}
        >
          {viewMode === '2d'
            ? 'Adjust the parameters to generate your unique pattern.'
            : 'Rotate and explore your pattern in 3D space.'}
        </p>
      </div>

      {/* Canvas Area - Base Layer */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          zIndex: 0,
        }}
      >
        {/* Webcam Background - Always show in 3D mode */}
        {viewMode === '3d' ? (
          <>
            {/* Webcam Layer */}
            <div
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
                zIndex: 1,
              }}
            >
              <Webcam
                ref={webcamRef}
                audio={false}
                screenshotFormat="image/jpeg"
                mirrored={true}
                videoConstraints={{
                  width: 1920,
                  height: 1080,
                  facingMode: 'user',
                }}
                onUserMedia={handleWebcamLoad}
                onUserMediaError={handleWebcamError}
                style={{
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                  display: 'block',
                }}
              />
            </div>
            {/* 3D Uniform on top of webcam */}
            <div
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
                zIndex: 2,
              }}
            >
              <UniformRenderer params={params} autoRotate key="uniform-renderer" transparentBackground={true} />
            </div>
          </>
        ) : (
          /* Normal rendering without webcam */
          <div style={{ width: '100%', height: '100%' }}>
            {viewMode === '2d' ? (
              <NoiseGradientCanvas params={params} />
            ) : (
              <UniformRenderer params={params} autoRotate key="uniform-renderer" transparentBackground={false} />
            )}
          </div>
        )}
      </div>

      {/* Name Input Modal */}
      {showNameModal && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            backdropFilter: 'blur(10px)',
            zIndex: 200,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
          onClick={() => setShowNameModal(false)}
        >
          <div
            style={{
              backgroundColor: 'rgba(255, 255, 255, 0.95)',
              backdropFilter: 'blur(20px)',
              borderRadius: '24px',
              padding: '20px',
              minWidth: '320px',
              boxShadow: '0 8px 32px rgba(0, 0, 0, 0.15)',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h3
              style={{
                fontSize: '14px',
                fontFamily: 'Helvetica, Arial, sans-serif',
                fontWeight: 600,
                color: 'rgba(0, 0, 0, 0.9)',
                marginBottom: '10px',
              }}
            >
              Archive Uniform
            </h3>

            {/* Divider */}
            <div
              style={{
                width: '100%',
                height: '1px',
                backgroundColor: 'rgba(0, 0, 0, 0.1)',
                marginBottom: '16px',
              }}
            />

            <p
              style={{
                fontSize: '10px',
                fontFamily: 'Helvetica, Arial, sans-serif',
                fontWeight: 400,
                color: 'rgba(0, 0, 0, 0.7)',
                marginBottom: '12px',
                lineHeight: typography.lineHeight.relaxed,
              }}
            >
              Enter a name for this uniform design:
            </p>

            <input
              type="text"
              value={uniformName}
              onChange={(e) => setUniformName(e.target.value)}
              placeholder="Uniform name"
              disabled={isSaving}
              style={{
                width: '100%',
                padding: '8px 12px',
                backgroundColor: '#E5E5E5',
                border: 'none',
                borderRadius: '8px',
                fontSize: '12px',
                fontFamily: 'Helvetica, Arial, sans-serif',
                fontWeight: 400,
                color: '#000000',
                outline: 'none',
                marginBottom: '16px',
              }}
              autoFocus
            />

            <div
              style={{
                display: 'flex',
                gap: '10px',
                justifyContent: 'flex-end',
              }}
            >
              <button
                onClick={() => {
                  setShowNameModal(false);
                  setUniformName('');
                }}
                disabled={isSaving}
                style={{
                  padding: '8px 16px',
                  backgroundColor: 'transparent',
                  borderRadius: '6px',
                  color: 'rgba(0, 0, 0, 0.7)',
                  fontSize: '12px',
                  fontFamily: 'Helvetica, Arial, sans-serif',
                  fontWeight: 400,
                  border: '1px solid rgba(0, 0, 0, 0.2)',
                  transition: `all ${interaction.duration.normal} ${interaction.easing.standard}`,
                  cursor: isSaving ? 'not-allowed' : 'pointer',
                  opacity: isSaving ? 0.5 : 1,
                }}
              >
                Cancel
              </button>

              <button
                onClick={handleSaveUniform}
                disabled={isSaving}
                style={{
                  padding: '8px 16px',
                  backgroundColor: '#000000',
                  borderRadius: '6px',
                  color: colors.dark.label.primary,
                  fontSize: '12px',
                  fontFamily: 'Helvetica, Arial, sans-serif',
                  fontWeight: 400,
                  border: 'none',
                  transition: `all ${interaction.duration.normal} ${interaction.easing.standard}`,
                  cursor: isSaving ? 'not-allowed' : 'pointer',
                  opacity: isSaving ? 0.7 : 1,
                }}
              >
                {isSaving ? 'Saving...' : 'Save'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
